MODEL_TYPE: 'bert_mcan'
BATCH_SIZE: 64
IMG_SEQ_LEN: 100
IMG_EMBED_SIZE: 2048
QUES_SEQ_LEN: 14
FEATURES_TYPE: 'bottom_up_100'
PRETRAIN: true
NUM_CLASSES: 3129
ANSWERS_TYPE: 'softscore'
DROPOUT_RATE: 0.1
HIDDEN_SIZE: 768
FLAT_MLP_SIZE: 512
FLAT_OUT_SIZE: 1536
NUM_LAYERS: 12
NUM_HEADS: 12
FF_SIZE: 3072
BASE_LEARNING_RATE: 5.0e-5
ADAM_BETA_1: 0.9
ADAM_BETA_2: 0.98
ADAM_EPSILON: 1.0e-9
