MODEL_TYPE: 'bert_hiealtcoatt'
BATCH_SIZE: 64
IMG_SEQ_LEN: 100
IMG_EMBED_SIZE: 2048
QUES_SEQ_LEN: 14
FEATURES_TYPE: 'bottom_up_100'
NUM_CLASSES: 3129
ANSWERS_TYPE: 'softscore'
DROPOUT_RATE: 0.2
HIDDEN_SIZE: 1024
NUM_LAYERS: 12
NUM_HEADS: 12
BASE_LEARNING_RATE: 2.0e-5
ADAM_BETA_1: 0.9
ADAM_BETA_2: 0.999
ADAM_EPSILON: 1.0e-7