MODEL_TYPE: 'bert_mcoatt'
BATCH_SIZE: 128
IMG_SEQ_LEN: 196
IMG_EMBED_SIZE: 2048
QUES_SEQ_LEN: 28
FEATURES_TYPE: 'resnet152'
NUM_CLASSES: 1000
ANSWERS_TYPE: 'mcq'
DROPOUT_RATE: 0.1
HIDDEN_SIZE: 512
NUM_LAYERS: 12
NUM_HEADS: 8
BASE_LEARNING_RATE: 3.0e-5
ADAM_BETA_1: 0.9
ADAM_BETA_2: 0.999
ADAM_EPSILON: 1.0e-7