MODEL_TYPE: 'bert_hiecoatt'
BATCH_SIZE: 128
IMG_SEQ_LEN: 196
IMG_EMBED_SIZE: 512
QUES_SEQ_LEN: 28
FEATURES_TYPE: 'vgg19'
NUM_CLASSES: 1000
ANSWERS_TYPE: 'modal'
DROPOUT_RATE: 0.5
HIDDEN_SIZE: 512
NUM_LAYERS: 12
NUM_HEADS: 8
BASE_LEARNING_RATE: 1.0e-4
ADAM_BETA_1: 0.9
ADAM_BETA_2: 0.999
ADAM_EPSILON: 1.0e-7